project_id = "bgdvlhttyjeuprrfxgun"

[functions.create-checkout-session]
verify_jwt = true

[functions.webhook-stripe]
verify_jwt = false

[functions.n8n-integration]
verify_jwt = true

[functions.gmail-integration]
verify_jwt = true

[functions.google-drive-integration]
verify_jwt = true

[functions.whatsapp-integration]
verify_jwt = true
